[features]
seeds = false
skip-lint = false


[programs.localnet]
ember_markets = "9ERQkbvkLhxTUfw4vpRpcAtxvsUorn7HEXrGSxY5F6Zy"
binary_outcome_tokens= "5c5A6f6HQNhgaSmwuKCkCcgEJWk9UoskR9S2Fp5ig6v1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
